const shopCards = [
    {type: 'Spell', name: 'Wingardium leviosa', gain: {coin: 1}, text: 'You may put Items you acquire on top of your deck instaed of in your discard pile.', price: 2},
    {type: 'Spell', name: 'Wingardium leviosa', gain: {coin: 1}, text: 'You may put Items you acquire on top of your deck instaed of in your discard pile.', price: 2},
    {type: 'Spell', name: 'Wingardium leviosa', gain: {coin: 1}, text: 'You may put Items you acquire on top of your deck instaed of in your discard pile.', price: 2},
    {type: 'Spell', name: 'Wingardium leviosa', gain: {coin: 1}, text: 'You may put Items you acquire on top of your deck instaed of in your discard pile.', price: 2},
    {type: 'Spell', name: 'Lumos', allGain: {card: 1}, text: '', price: 4},
    {type: 'Spell', name: 'Lumos', allGain: {card: 1}, text: '', price: 4},
    {type: 'Spell', name: 'Disendo', gain: {damage: 2}, text: '', price: 5},
    {type: 'Spell', name: 'Disendo', gain: {damage: 2}, text: '', price: 5},
    {type: 'Spell', name: 'Incendiodo', gain: {damage: 1, card: 1}, text: '', price: 4},
    {type: 'Spell', name: 'Incendiodo', gain: {damage: 1, card: 1}, text: '', price: 4},
    {type: 'Spell', name: 'Incendiodo', gain: {damage: 1, card: 1}, text: '', price: 4},
    {type: 'Spell', name: 'Incendiodo', gain: {damage: 1, card: 1}, text: '', price: 4},
    {type: 'Spell', name: 'Reparo', choose: {coin: 2, card: 1}, text: '', price: 3},
    {type: 'Spell', name: 'Reparo', choose: {coin: 2, card: 1}, text: '', price: 3},
    {type: 'Spell', name: 'Reparo', choose: {coin: 2, card: 1}, text: '', price: 3},
    {type: 'Spell', name: 'Reparo', choose: {coin: 2, card: 1}, text: '', price: 3},
    {type: 'Spell', name: 'Reparo', choose: {coin: 2, card: 1}, text: '', price: 3},
    {type: 'Spell', name: 'Reparo', choose: {coin: 2, card: 1}, text: '', price: 3},
    {type: 'Item', name: 'Quidditch gear', gain: {damage: 1, health: 1}, text: '', price: 3},
    {type: 'Item', name: 'Quidditch gear', gain: {damage: 1, health: 1}, text: '', price: 3},
    {type: 'Item', name: 'Quidditch gear', gain: {damage: 1, health: 1}, text: '', price: 3},
    {type: 'Item', name: 'Quidditch gear', gain: {damage: 1, health: 1}, text: '', price: 3},
    {type: 'Item', name: 'Essence of dittany', anyOne: {health: 2}, text: '', price: 2},
    {type: 'Item', name: 'Essence of dittany', anyOne: {health: 2}, text: '', price: 2},
    {type: 'Item', name: 'Essence of dittany', anyOne: {health: 2}, text: '', price: 2},
    {type: 'Item', name: 'Essence of dittany', anyOne: {health: 2}, text: '', price: 2},
    {type: 'Item', name: 'Golden snitch', gain: {coin: 2, card: 1}, text: '', price: 5},
    {type: 'Item', name: 'Sorting hat', gain: {coin: 2}, text: 'You may put Allies you acquire on top of your deck instaed of in your discard pile.', price: 4},
    {type: 'Ally', name: 'Rubeus Hagrid', gain: {damage: 1}, allGain: {health: 1}, text: '', price: 4},
    {type: 'Ally', name: 'Oliver Wood', gain: {damage: 1}, text: 'If you defeat a Villian. Any one Hero gains 2 health', price: 3},
    {type: 'Ally', name: 'Albus Bumbledore', allGain: {damage: 1, coin: 1, health: 1, card: 1}, text: '', price: 8},
]

export default shopCards